### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by noudadrichem** [Gobluebro/Geekhack-scraper#18]
> Since this solution is based on automated scraping of data and then displaying said data, issues arise when you cannot predict how someone might structure their post.

This is also the issue I was stumbling across when making an attempt on scraping GH to fill up https://keycapsets.com/
Do you have some solid ideas on how you/we could solve something like this? Would love te be able to fill up KCS automagically instead of manually updating the DB.

**Comment by Gobluebro** [comment]
Hello!

I do believe that this scraper will still require a certain amount of manual work / user review but I can try to accommodate handling what I can.

I took a look at your website and noticed that it is only keycaps as the website name suggests. Currently there is no way to determine if a thread is a keycap set or not. I could possibly check the title for a number of known names for keycap profiles. That could still be ambiguous but it would possibly make it less manual. Would that be a good feature for you?

Do you have any specific requests for data to get back from a thread?

**Comment by Gobluebro** [comment]
@noudadrichem Hello. Have you gotten the chance to look at my reply? I will close this due to inactivity soon.

**Comment by noudadrichem** [comment]
Hi! I'm sorry I missed your reply as it was blazing fast! 

A bit of manual work is okay. If it's less than manual input it's always a plus! I looked at some of the code but couldn't get it to work, does it fetch more than images? Like actual data like dates and name etc? 

It would be amazing if you could pick this up but I won't bother to do this together as well! We can hop on a Discord chat/call if you want! (My Discord = `Noud | keycapsets.com#9634`)

The ideal scenario would be to have keycap set info like:
- name
- designer (mostly the Geekhack user itself)
- current status (e.g. IC or GB)
- if GB
  - start date
  - end date
- Brand
- Material
- Vendors
- Kitting (name/type + img)
- Renders

This is a big list and hard to scrape! Haha But having like 50% autofilled is a big plus! Especially the images/renders etc.

**Comment by Gobluebro** [comment]
> The ideal scenario would be to have keycap set info like:
> 
>     * name
> 
>     * designer (mostly the Geekhack user itself)
> 
>     * current status (e.g. IC or GB)
> 
>     * if GB
>       
>       * start date
>       * end date
> 
>     * Brand
> 
>     * Material
> 
>     * Vendors
> 
>     * Kitting (name/type + img)
> 
>     * Renders
> 
> 
> This is a big list and hard to scrape! Haha But having like 50% autofilled is a big plus! Especially the images/renders etc.

@noudadrichem 
Take a look at [threadscrape.ts](https://github.com/Gobluebro/Geekhack-scraper/blob/master/geekhack-scraper/threadscrape.ts)

We get back these from your list:

- Title of the group buy / IC. (name)
- The author of the thread. (designer)
- The thread start date, the thread modified date, and the thread scraped date. (probably not what you actually want of start/end date)
- all the images on the thread post including kits and renders.

this isn't on threadscrape.ts but this is on [index.ts](https://github.com/Gobluebro/Geekhack-scraper/blob/master/geekhack-scraper/index.ts) 
I haven't allowed IC threads in this current iteration to be scraped but it has been in the past and it's merely just another line of code to add and whether it's an IC or GB is easy to determine. 

Some questions I have is:
Brand, I assume is things like GMK, SA, KAT. So maybe a mixture of brand names/profiles. I think could be done but would miss group buys with new profiles/manufacturers when they first come out.
Material, I assume this is basically determining ABS or PBT. 

As for the rest, these are probably the most difficult parts:
- A true start and end date of group buys.

This is difficult as you never know where a person is going to put these in their group buy. Sometimes it's in the title, sometimes it's in the post. Different date formats. They don't always have "Start" and "End" next to them. There is a lot of human factors of determining these things. I have considered trying to scrape this in the past and hope to be able to try and "guess" what the start and end dates might be in the future but currently it is not possible. 

- Vendors
This is a little difficult though I could see possibly a solution being just to search for links that include a certain url of a known vendor since that seems to be pretty consistent. It's hard to only grab just the word "Vendors" as it's not always labeled as such. Or even sometimes it is an image with the word "Vendors" on it.

- Kitting
This can also be difficult. Kits are not always named the same. Some say base or some just have a random name for their bases. Sometimes they don't even say anything, they have an image to describe it instead.

If you want an example of a group buy that is hard to scrape for information, check out the [GMK Hunt GB thread](https://geekhack.org/index.php?topic=115532.0)

It would probably be easier to scrape a vendor site for that valuable information than it would be scraping geekhack. I do believe that geekhack is probably the place where all group buys will exist at any given time. I don't believe geekhack will ever change to include some programmatic way of getting this information that a group buy user must fill out. It's a shame.

**Comment by noudadrichem** [comment]
> Brand, I assume is things like GMK, SA, KAT.
GMK is a brand, SA and KAT are profiles. A mistake I made when I started KCS 2 years ago! haha.

> A true start and end date of group buys.
We could look up different formats with regexes. But indeed hard to determine what is right.

> It would probably be easier to scrape a vendor site for that valuable information than it would be scraping geekhack.
This is a good idea. 

Geekhack indeed makes it hard to scrape. But that makes Geekhack Geekhack! haha. So many people challenged this. It's amazing.

I still aim to make Keycapset a more go-to platform so starters understand what is going on in the hobby, but also create a tool for designers so they can gather information about their potential buyers in form of ICs (https://keycapsets.com/ic/gmk-test-cherry) or promote their set with custom websites (https://keycapsets.com/promote-your-keycapset).

**Comment by Gobluebro** [comment]
> GMK is a brand, SA and KAT are profiles. A mistake I made when I started KCS 2 years ago! haha.

I am aware, I'm still trying to grasp what is being requested. Okay so you don't want profiles. But you want the code to make the determination for you about brands. Since KAT keycap threads are never labeled as "Keyreative" and SA keycap threads are never labeled as SP (Signature Plastics). Is there no use at all for profile?

Thankfully things like GMK, KAT, ePBT, MW, MT3, DSS are easy to understand which brands/profiles they are so it wouldn't be too much of an issue. 

Things like SA we might have to make assumptions on, if it doesn't say Maxkey then we have to assume it's SP.

**Comment by noudadrichem** [comment]
Ye, we can attract data from other data. Like brands from profiles etc.
Profiles and other attributes are used to filter the sets. 

> I'm still trying to grasp what is being requested.  

This is an example of a Keycapset object: https://api.keycapsets.com/s/60a625ee042f4c01e424c0dc 
So, every key that can be autofilled is a plus! haha

**Comment by Gobluebro** [comment]
Vendor scraping has been [officially released since this commit](https://github.com/Gobluebro/Geekhack-scraper/commit/6042a84e9bbf81a444a03366bf2537e8969cd2b1)

**Comment by Gobluebro** [comment]
@noudadrichem 

"Brand" scraping has been [officially released since this commit.](https://github.com/Gobluebro/Geekhack-scraper/commit/4b993a3ff0a7b5b4603930b5face1f139142dfd9)

This probably won't be exactly how you do your brands. Nor is labeled as "brands". This is more of an identifier of keycaps. Take a look at [keycaps.ts](https://github.com/Gobluebro/Geekhack-scraper/blob/master/utils/keycaps.ts). We save the `KeycapIdentifier ` enum value into the database. You are free to modify this in your own fork as you wish. There is more info as well like profile and company that is currently being unused. You are free to use this as well in whatever way you wish. 

I believe that this and vendors is probably the best that can be done. I will not attempt dates because it's just not feasible on geekhack. I'd rather just scrape the vendors instead. I hope this helps. Good luck.

**Comment by noudadrichem** [comment]
Amazing! Thank you. I'll take a look!
